apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-op-kube-prometh-prometheus.logs:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-op-kube-prometh-alertmanager.logs:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
kind: ConfigMap
metadata:
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.10.0
  name: cm-grafana-datasource
  namespace: logs
