apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: grafana-central
    app.kubernetes.io/version: 10.1.5
  name: grafana
  namespace: logs
spec:
  endpoints:
  - honorLabels: true
    path: /metrics
    port: http-web
    scheme: http
    scrapeTimeout: 30s
  jobLabel: prometheus-op
  namespaceSelector:
    matchNames:
    - logs
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-central
